### ISSUE TITLE
CJS lib issue "TypeError: invariant is not a function"

### ISSUE THREAD

**Issue by ep-mark** [yozorajs/yozora#17]
When you try and use the `DefaultParser` from `@yozora/core-parser` using the cjs lib you get the following error:

```javascript
TypeError: invariant is not a function
    at consumeNewOpener (https://cigod8.csb.app/node_modules/@yozora/core-parser/lib/cjs/index.cjs:143:13)
    at Object.consume (https://cigod8.csb.app/node_modules/@yozora/core-parser/lib/cjs/index.cjs:303:13)
    at matchBlockTokens (https://cigod8.csb.app/node_modules/@yozora/core-parser/lib/cjs/index.cjs:793:27)
    at Object.process (https://cigod8.csb.app/node_modules/@yozora/core-parser/lib/cjs/index.cjs:736:32)
    at CustomParser.parse (https://cigod8.csb.app/node_modules/@yozora/core-parser/lib/cjs/index.cjs:975:32)
    at Object.eval (https://cigod8.csb.app/src/CustomParser.test.ts:15:25)
    at https://codesandbox.io/static/js/3.09a963795.chunk.js:1:338381
    at new Promise (<anonymous>)
    at t.callAsyncFn (https://codesandbox.io/static/js/3.09a963795.chunk.js:1:338040)
    at https://codesandbox.io/static/js/7.916d1bd34.chunk.js:1:6522
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:4328)
```

Here is a code sandbox for the problem:
https://codesandbox.io/s/delicate-haze-cigod8?file=/index.html

The `@yozora/invariant/lib/cjs/index.cjs` looks like:
```javascript
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });
...
function invariant(condition, message) {
    ...
}

exports.default = invariant;
exports.invariant = invariant;
```

which comes from https://github.com/yozorajs/yozora/blob/main/packages/invariant/src/index.ts
```typescript
export function invariant(
  condition: boolean,
  message?: string | (() => string),
): asserts condition {
  ...
}

export default invariant
```
The problem occurs when `@yozora/core-parse/lib/cjs/index.cjs` requires the `@yozora/invariant'`, expecting the default to be the `invariant` function.
```javascript
var invariant = require('@yozora/invariant');
```
But for this to work it would need to use the default:
```javascript
var invariant = require('@yozora/invariant').default;
```

I am no rollup expert but I think it may be something to do with this issue: https://github.com/rollup/rollup/issues/1961

Thanks

**Comment by guanghechen** [comment]
Hi @ep-mark , thank you for trying out `yozora`, the issue you reported is ACK, and I will take the time to fix it. Maybe I will remove all default export of all packages under this monorepo, which would completely avoid this bundle issue (this is a breaking change, but I think it's okay since there are no third-party dependencies).

**Comment by ep-mark** [comment]
@guanghechen That fixed it! Thanks!
